### ISSUE TITLE
Separate generation from test-reporter

### ISSUE THREAD

**Issue by xeronimus** [scenarioo/scenarioo-js#10]
As a developer I want to be able to use scenarioo-js in different environments, independent from my webtest library (protractor / webdriverJS / webdriver.io).
# Acceptance Criteria
- scenarioo-js has no hard dependency to jasmine 
- scenarioo-js has no hard dependency to protractor
- scenarioo-js provides two standard adaptors : one for webdriverJS, one for webdriver.io
- scenarioo-js provides hooks in order to support writing own/custom adaptors

**Comment by bruderol** [comment]
@xeronimus I am not sure, if this can be closed?

**Comment by bruderol** [comment]
@xeronimus: what is the state with this? What will we do with that? Is it okay, as it is now or what would be missing?

**Comment by bruderol** [comment]
ok, got no feedback from @xeronimus, I am now closing this, since I think it is okay, otherwise womone can reopen or report about issues with that.
