### ISSUE TITLE
Use "failed" instead of "fail" as unsuccessful status value

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo-js#11]
See Java implementation:

https://github.com/scenarioo/scenarioo-java/blob/develop/src/main/java/org/scenarioo/model/docu/entities/Status.java

	/**
	 * Status for successfully succeeded and tested without errors.
	 */
	SUCCESS("success"),
	
	/**
	 * Status for failed testing the corresponding step, scenario, use case or build.
	 */
	FAILED("failed");

**Comment by xeronimus** [comment]
hi @adiherzog .  I think this is already fixed in develop?

**Comment by adiherzog** [comment]
ok thanks :+1:
