### ISSUE TITLE
Screen annotation support

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo-js#13]
See: https://github.com/scenarioo/scenarioo/issues/149

**Comment by bruderol** [comment]
This feature is covered on the current develop branch.

**Comment by bruderol** [comment]
currently not realy useful, because very hard to get the coordinates of an element in protractor.

**Comment by bruderol** [comment]
I think that the writer is okay, but a lot of convenience is missing, see #25 and #27

**Comment by bruderol** [comment]
I close this, because it works for now, and we can add convenience later.
