### ISSUE TITLE
ScenariooJS Release 3.0

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo-js#21]
Release 3.0 Preparations:

[x] Release Notes prepared
[x] Docu and Migration Guide prepared
[x] Changelog prepared
[x] checked for remaining TODOs - didnt find any
[x] prepare version

**Comment by xeronimus** [comment]
update: as discussed, if the left-over todos are done, this is ready to be merged into master and released..

**Comment by bruderol** [comment]
I merged everything between develop and release branch.

Currently release prepration should be done on release-2.2 branch and then merged to develop (and finally to master). 

Thank you @xeronimus for helping us.

I will try to get the remaining TODOs fixed as soon as possible.

I see one last problem:
I had a look at the generated API docu and it seems to me, that this is not realy understandable, as it seems to me. Te most important things are missing, e.g. I did not find the documentation for the global `scenarioo` object. We should have a look at this.

**Comment by bruderol** [comment]
except for the docu, the current state on the release-2.2 branch should be in a good state to be ready to be released.

Although there is still room for improvement concerning screen annotations and other step data.

But I think we could release the current state and then improve on the other remaining issues in version 3.0

**Comment by bruderol** [comment]
@adiherzog @dola I decided: We will release it as "3.0" - just to be up to date together with our other forthcoming release. We will release this kind of together more or less. I hope you can agree?

**Comment by adiherzog** [comment]
@bruderol Yes, that's fine.

**Comment by bruderol** [comment]
Release of ScenariooJS is prepared, will test is a little bit and then release it.

@adiherzog @mi-we  @dola 
I will keep the inofficial "release-2,2*-branch - for using the very new features (like typings) and testing the release you have to use currently "release-3.0"-branch, if you allready want the newest version, didnt wnat to accidentaly break any project using the old release candidate branch.

**Comment by bruderol** [comment]
@adiherzog @mi-we @dola 
I did it. 3.0.0 now officially released.
You can start to use it in your projects from npm (no need to use the release branch url anymore).
