### ISSUE TITLE
Improve Logging

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo-js#23]
Scenario Logging is verbose, which has some advantages, but should be a little bit more nice and also should be possible to disable.

Before implementing this issue it looked similar to the following:
```
scenario :: scenario 1 :: suceeded
.scenario :: scenario 2 :: suceeded
.scenario :: scenario 3 :: suceeded
.useCase :: usecase 1 :: suceeded (3 passed, 0 failed, 0 skipped)
```

following has been improved:
* each loged scenario and use case should start on a new line, and not on the F/./*-outcome line of jasmine that belongs to the last run test
* the `.` and `F` and `*` from jasmine should be logged together with scenarioo's scenario outcome log they belong too, instead of on a new line
* also all other output of a scenario needs to be on a new line (add new line before scenario starts)
* use case name of scenario should belong to the full name being logged
* use ansi colors to highlight each scenarios outcome with colors
* switch to disable scenarioo logging for those projects that don't like it
* log status in front of each line, to immediately see what status it is.

**Comment by bruderol** [comment]
Started to improve some of the mentioned points, now it looks as follows:

![image](https://cloud.githubusercontent.com/assets/755721/15269143/7c522096-19f6-11e6-9ef2-f6c83ecc6064.png)

**Comment by bruderol** [comment]
there is now 1 line for each scenario in correct color and followed by the usual jasmine */./F output (did not manage to put this on the same line unfortunately (maybe on linux it will work).

**Comment by bruderol** [comment]
the use case lines are kept black, because that is just additional summary and not a real failed or succeeded test on its own

**Comment by bruderol** [comment]
@dola what do you think? Okay like this?

**Comment by bruderol** [comment]
I updated the issue description to reflect current state.

**Comment by dola** [comment]
@bruderol looks pretty cool with the colors! Will have a look at the code next week.

**Comment by bruderol** [comment]
you can see a sample output here: 
http://build.scenarioo.org/jenkins/job/deploy-demo-and-run-e2e-tests/824/console

**Comment by bruderol** [comment]
finally managed to even make it better:

![image](https://cloud.githubusercontent.com/assets/755721/15277085/008b608a-1afa-11e6-9a26-ebf75cc0370f.png)

**Comment by bruderol** [comment]
consider this as done
