### ISSUE TITLE
Improve documentation for label definitions in fluent DSL

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo-js#47]
After adding a label on the scenario level I get this error when executing the test:

```
Step title: Failed: Failed: Label "happy-case" is not defined in your project as a valid label for scenario. Please use `scenarioo.fluentDslConfig.scenarioLabelDefinitions` to define your labels. Currently defined labels allowed in a scenario are: {}
```

@bruderol Why do I have to define the valid labels separately? This is not required in the Java Writer and I did not find any documentation about it.

**Comment by bruderol** [comment]
@adiherzog it is not a bug, it is a feature, and it is only the case when using the Fluent DSL. The error explains it to you, what you have to do. Is this not understandable? And I think it is a good thing to check that developers do not start to use labels without clearly defining them, to prevent "Label Wildwuchs".

If this disturbs you we can make it configurable, whether to enforce label definitions or not. But I think this is in general a good thing.

See following places where it is documented (not optimal, but at least):
* examples: https://github.com/scenarioo/scenarioo-js/blob/develop/example/test/exampleFluentDslLabelDefinitions.js
* TypeScript Typings: `fluentDslConfig` and type `FluentDslConfig`

Is this ok for you?

**Comment by adiherzog** [comment]
Ok, I can live with that. I was just quite surprised because it's not consistent with the other Writers we have.

Let's improve the documentation a bit. I think a markdown file for the labels feature or maybe for the entire fluent DSL would be good.

**Comment by bruderol** [comment]
yes, ok, agree. The ScenariooJS is in general conceptually inconsistent with the other writers.

**Comment by adiherzog** [comment]
I renamed the title of this item to just update the documentation.

1. The hint in the error message is not 100% correct and needs to be corrected (`scenarioo.fluentDslConfig.scenarioLabelDefinitions` should be `scenarioo.fluentDslConfig.scenarioLabels`.

2. We should add a *.md file documenting the feature with an example.

Here's an example for the documentation:

```
      scenarioo.fluentDslConfig.useCaseLabels = {
        'admin': 'Use case only accessible with the admin role',
        'anonymous': 'Use case also accessible without authentication'
      };
      scenarioo.fluentDslConfig.scenarioLabels = {
        'happy path': 'Typical useage scenario'
      };
```

**Comment by bruderol** [comment]
@adiherzog Yes, agree, please make a PR - Example is allready available and linked in the markdown documentation: see https://github.com/scenarioo/scenarioo-js/blob/develop/example/test/exampleFluentDslLabelDefinitions.js

**Comment by dola** [comment]
Added documentation here:
https://github.com/scenarioo/scenarioo-js/tree/feature/%2347-fluent-dsl-label-definitions#using-labels-with-the-fluent-dsl
Error message is also fixed and typings extended to be export individual subinterfaces.

**Comment by bruderol** [comment]
Thanks @dola for improving this - please see my improvements on the PR and merge!
