### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by dola** [scenarioo/scenarioo-js#53]
After a decision by all contributors, the license will be changed to MIT.

Todo:
 - change license file
 - update license in package.json

Maybe:
 - add header to all files with license (would not recommend)

**Comment by dola** [comment]
PR #54 contains the necessary changes:
 - new LICENSE file with MIT license (rename from LICENSE.txt)
 - remove license from source code file headers (was in index.js)
 - add to changelog for version 3.0.2
 - reference LICENSE file in README.md
 - build entire project

**Comment by bruderol** [comment]
@adiherzog and @dola i close this
