### ISSUE TITLE
Puppeteer?

### ISSUE THREAD

**Issue by xeronimus** [scenarioo/scenarioo-js#57]
Evaluation of "headless chrome API" aka "Puppeteer" for scenarioo-js.

https://github.com/GoogleChrome/puppeteer

Does dis replace WebdriverJS / Protractor?

**Comment by bruderol** [comment]
Interesting. Thanks. First thing interesting to mention: this works only with chrome, so this locks your tests to one browser - also it might not come with advantage of distributed browser tests - as far as I understood - so might be problematic if you need to parallelize hughe sets of tests - which you can do using selenium's grid capabilities - just my first thoughts - me personally I would give webdriver.io a try as another alternative or stick to protractor - but definitively an interesting candidate as well to keep an eye on, depending on your use case. Any other thoughts?

**Comment by danielsuter** [comment]
Headless chrome is not limited to puppeteer. You can easily run protractor tests headless as well. So this should not be a consideration.

**Comment by bruderol** [comment]
I think we can close this. If you diagree feel free to reopen. Thanks
