### ISSUE TITLE
Report Steps with Annotation/Decorator on TypeScript PageObjects

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo-js#59]
As a user I want scenarioo to automatically report a step on each call to functions on page objects, with a description of that function as step text, if that  function is annotated with a typescript decorator `reportStep`, such that I do not have to write the description of the step manually anymore.

Accpetance criteria
* calls to page object functions annotated with decorator `reportStep` are automatically reported as steps into scenarioo documentation
* all usual step parameters can be passed on the steps decorator.
* by default the description of the step is generated from the page object class name followed by the name of the page object function

**Comment by bruderol** [comment]
@sebastianzillessen I opened this for your PR.

**Comment by sebastianzillessen** [comment]
@bruderol I updated this, waiting for your feedback.

**Comment by bruderol** [comment]
@sebastianzillessen and @danielsuter thanks tousand for your great effort!
I think we should release the changes soon, will try to do it soon. Thanks for awesome work!
