### ISSUE TITLE
Fix broken links in docu due to release 4.0 and link js quickstart guide

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo-js#62]
* [x] Links in README.md are fixed (on to the viewer setup is broken)
* [x] the links are also fixed on npmjs.com
* [x] Link to the new Quickstart-JS Guide is added

**Comment by eggerschwiler** [comment]
Readme.md was updated in branch feature/prepare-for-next-release.
npmjs.com should be updated once the new version is released.

**Comment by davidlahner** [comment]
Version 4.0 of scenarioo-js has been released with the updated Readme.
