### ISSUE TITLE
Migrate our Examples to not using browser control flow but asynch await

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo-js#64]
Has been partialy done by @adiherzog but seems to be a mess now:

https://github.com/scenarioo/scenarioo-js/blob/7f022ee8896a9eafe35e94a66b6c473085449149/example/test/exampleFluentDslWithTypeScript.spec.ts#L74

There are obviously many awaits missing even in that one test where Adrian started to add them.

@adiherzog we have to clean that up!

I would guess that also for the step calls the `await` is needed!

**Comment by adiherzog** [comment]
Yes, that's right, thanks for noting.

**Comment by adiherzog** [comment]
@bruderol @danielsuter Done. All open PRs are merged now.
