### ISSUE TITLE
Inconsistent page object method names in example

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo-js#69]
https://github.com/scenarioo/scenarioo-js/blob/a199951218c1f356a3762b51004c7d70ae6b3a9e/example/test/pages/startPage.ts#L25

Only one page object method got renamed by @sebastianzillessen after review comment by @danielsuter - now it is confusingly inconsistent.

 Once ‘click...’ other is ‘select...’ both should be ‘select...’

**Comment by danielsuter** [comment]
Agree, will fix it. Good catch.

**Comment by sebastianzillessen** [comment]
Thanks @danielsuter for fixing this and @bruderol for spotting it !
